Diffuse Lighting[CLOSE THE WINDOW PULL REQUEST FIRST BEFORE MERGING THIS ONE]
NHLStenden-HBO-ICT-SE/graphics_22-23-graphics-groep-2 pull request #26
Opened 2022-10-05 13:32 UTC by JobNNHL

Currently lights work + colored lights.
Multiple lights only work if they're all white otherwise you'll get some weird visual glitches with color.
This is due to a math error that will be fixed in its own branch.
Multiple lights will be fixed in its own branch.

2022-10-05 14:22 UTC, kajatrijsburg requested changes
Vector3:
-in de distance functie word this.getX() gebruikt, mag x worden of this.x (x is private dus dat kan alleen binnen de class gebruikt worden. distance() staat binnen de class.)

Renderer:
(comments zijn echt super goed!)
-in ClampColor:
--ik zou een functie clamp(double num, double max, souble min) aan maken om code duplication tegen te gaan
--en dan misschien zelfs een Vector3.clamp(double min, double max)

2022-10-05 14:29 UTC, kajatrijsburg commented
(changes requested)

2022-10-06 07:55 UTC, JobNNHL commented
Applied and pushed the requested changes

2022-10-06 11:33 UTC, kajatrijsburg requested changes
Het enige wat hier nog mist een een test voor de Vector3 getDistance

2022-10-06 11:47 UTC, merged