Model loader
NHLStenden-HBO-ICT-SE/graphics_22-23-graphics-groep-2 pull request #29
Opened 2022-10-11 09:28 UTC by AlissaDeVegt

2022-10-11 12:22 UTC, kajatrijsburg requested changes
Ik denk dat het beter zou zijn als model Intersectable extend. Dan kunnen models in de Intersectable array van scene. 

Dan hoeven er ook geen changes in de renderer & scene gemaakt te worden.

Ik sta natuurlijk open voor argumenten om het anders te doen als je een betere manier weet.

2022-10-11 13:39 UTC, AlissaDeVegt commented
als dus zou extenden dan krijgt hij een intersectable methode mee maar wat zou daar dan in komen te staan? hoe zou dat dan geregeld worden met de triangles?

2022-10-11 18:13 UTC, kajatrijsburg commented
De methods kan op dezelfde manier geimplementeerd worden zoals dat nu in scene gebeurt.

2022-10-12 10:57 UTC, AlissaDeVegt commented
moet er dus nog wat aangepast worden? behalve de conflicts?

2022-10-13 18:16 UTC, AlissaDeVegt commented
modeloader methoden private, move position bug gefixt, shading ook gefixed + size aanpassen toegevoegd.

2022-10-14 17:51 UTC, kajatrijsburg approved these changes

2022-10-14 17:52 UTC, merged